fix: error handling decorator for ember-concurrency tasks
projectcaluma/ember-emeis pull request #386
Opened 2022-01-25 16:42 UTC by czosel

2022-01-25 16:48 UTC, anehx requested changes
LGTM, but where is the test?

2022-01-27 17:22 UTC, czosel commented
Added a test :star2:

2022-01-27 17:37 UTC, derrabauke approved these changes

2022-01-27 17:38 UTC, merged

2022-01-27 18:41 UTC, czosel commented
:tada: This PR is included in version 3.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-emeis/v/3.1.1)
- [GitHub release](https://github.com/projectcaluma/ember-emeis/releases/tag/v3.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: