fix: always sort scopes client-side
projectcaluma/ember-emeis pull request #583
Opened 2022-11-17 16:32 UTC by czosel

This is important when the ember store already contains data and we can't rely on the sort in the API response.

Based on #584

2022-11-17 16:34 UTC, winged requested changes

2022-11-17 16:35 UTC, czosel commented on addon/templates/scopes/edit.hbs
> +            @model={{sort-by "full-name" this.allScopes}}
fixed

2022-11-17 16:35 UTC, winged approved these changes

2022-11-17 16:44 UTC, winged approved these changes
LGTM!

2022-11-18 08:06 UTC, merged

2022-11-18 08:08 UTC, czosel commented
:tada: This PR is included in version 6.2.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-emeis/v/6.2.3)
- [GitHub release](https://github.com/projectcaluma/ember-emeis/releases/tag/v6.2.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: